/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonVariant, IconPosition, Mode } from "./interface";
export { ButtonVariant, IconPosition, Mode } from "./interface";
export namespace Components {
    interface NjwdsAlert {
        "noIcon": boolean;
        "slim": boolean;
        "type": "default" | "info" | "warning" | "error" | "emergency";
    }
    interface NjwdsBanner {
    }
    interface NjwdsButton {
        "icon"?: string;
        "iconPosition": IconPosition;
        "iconTitle"?: string;
        "mode": Mode;
        "variant": ButtonVariant;
    }
    interface NjwdsIcon {
        "decorative": boolean;
        "icon": string;
        "iconTitle"?: string;
        "size": "3" | "4" | "5" | "6" | "7" | "8" | "9" | "scale";
    }
}
declare global {
    interface HTMLNjwdsAlertElement extends Components.NjwdsAlert, HTMLStencilElement {
    }
    var HTMLNjwdsAlertElement: {
        prototype: HTMLNjwdsAlertElement;
        new (): HTMLNjwdsAlertElement;
    };
    interface HTMLNjwdsBannerElement extends Components.NjwdsBanner, HTMLStencilElement {
    }
    var HTMLNjwdsBannerElement: {
        prototype: HTMLNjwdsBannerElement;
        new (): HTMLNjwdsBannerElement;
    };
    interface HTMLNjwdsButtonElement extends Components.NjwdsButton, HTMLStencilElement {
    }
    var HTMLNjwdsButtonElement: {
        prototype: HTMLNjwdsButtonElement;
        new (): HTMLNjwdsButtonElement;
    };
    interface HTMLNjwdsIconElement extends Components.NjwdsIcon, HTMLStencilElement {
    }
    var HTMLNjwdsIconElement: {
        prototype: HTMLNjwdsIconElement;
        new (): HTMLNjwdsIconElement;
    };
    interface HTMLElementTagNameMap {
        "njwds-alert": HTMLNjwdsAlertElement;
        "njwds-banner": HTMLNjwdsBannerElement;
        "njwds-button": HTMLNjwdsButtonElement;
        "njwds-icon": HTMLNjwdsIconElement;
    }
}
declare namespace LocalJSX {
    interface NjwdsAlert {
        "noIcon"?: boolean;
        "slim"?: boolean;
        "type"?: "default" | "info" | "warning" | "error" | "emergency";
    }
    interface NjwdsBanner {
    }
    interface NjwdsButton {
        "icon"?: string;
        "iconPosition"?: IconPosition;
        "iconTitle"?: string;
        "mode"?: Mode;
        "variant"?: ButtonVariant;
    }
    interface NjwdsIcon {
        "decorative"?: boolean;
        "icon"?: string;
        "iconTitle"?: string;
        "size"?: "3" | "4" | "5" | "6" | "7" | "8" | "9" | "scale";
    }
    interface IntrinsicElements {
        "njwds-alert": NjwdsAlert;
        "njwds-banner": NjwdsBanner;
        "njwds-button": NjwdsButton;
        "njwds-icon": NjwdsIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "njwds-alert": LocalJSX.NjwdsAlert & JSXBase.HTMLAttributes<HTMLNjwdsAlertElement>;
            "njwds-banner": LocalJSX.NjwdsBanner & JSXBase.HTMLAttributes<HTMLNjwdsBannerElement>;
            "njwds-button": LocalJSX.NjwdsButton & JSXBase.HTMLAttributes<HTMLNjwdsButtonElement>;
            "njwds-icon": LocalJSX.NjwdsIcon & JSXBase.HTMLAttributes<HTMLNjwdsIconElement>;
        }
    }
}
