/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonVariant } from "./components/button/button";
import { Mode } from "./interface";
export { ButtonVariant } from "./components/button/button";
export { Mode } from "./interface";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface NjwdsAlert {
        "noIcon": boolean;
        "slim": boolean;
        "type": "default" | "info" | "warning" | "error" | "emergency";
    }
    interface NjwdsBanner {
    }
    interface NjwdsButton {
        "asChild": boolean;
        "mode": Mode;
        "variant": ButtonVariant;
    }
    interface NjwdsRadio {
        "inputId": string;
        "tile": boolean;
        "value": string;
    }
    interface NjwdsRadioGroup {
        "name": string;
        "required": boolean;
        "tile": boolean;
        "value": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNjwdsAlertElement extends Components.NjwdsAlert, HTMLStencilElement {
    }
    var HTMLNjwdsAlertElement: {
        prototype: HTMLNjwdsAlertElement;
        new (): HTMLNjwdsAlertElement;
    };
    interface HTMLNjwdsBannerElement extends Components.NjwdsBanner, HTMLStencilElement {
    }
    var HTMLNjwdsBannerElement: {
        prototype: HTMLNjwdsBannerElement;
        new (): HTMLNjwdsBannerElement;
    };
    interface HTMLNjwdsButtonElement extends Components.NjwdsButton, HTMLStencilElement {
    }
    var HTMLNjwdsButtonElement: {
        prototype: HTMLNjwdsButtonElement;
        new (): HTMLNjwdsButtonElement;
    };
    interface HTMLNjwdsRadioElement extends Components.NjwdsRadio, HTMLStencilElement {
    }
    var HTMLNjwdsRadioElement: {
        prototype: HTMLNjwdsRadioElement;
        new (): HTMLNjwdsRadioElement;
    };
    interface HTMLNjwdsRadioGroupElement extends Components.NjwdsRadioGroup, HTMLStencilElement {
    }
    var HTMLNjwdsRadioGroupElement: {
        prototype: HTMLNjwdsRadioGroupElement;
        new (): HTMLNjwdsRadioGroupElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "njwds-alert": HTMLNjwdsAlertElement;
        "njwds-banner": HTMLNjwdsBannerElement;
        "njwds-button": HTMLNjwdsButtonElement;
        "njwds-radio": HTMLNjwdsRadioElement;
        "njwds-radio-group": HTMLNjwdsRadioGroupElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface NjwdsAlert {
        "noIcon"?: boolean;
        "slim"?: boolean;
        "type"?: "default" | "info" | "warning" | "error" | "emergency";
    }
    interface NjwdsBanner {
    }
    interface NjwdsButton {
        "asChild"?: boolean;
        "mode"?: Mode;
        "variant"?: ButtonVariant;
    }
    interface NjwdsRadio {
        "inputId": string;
        "tile"?: boolean;
        "value": string;
    }
    interface NjwdsRadioGroup {
        "name": string;
        "required"?: boolean;
        "tile"?: boolean;
        "value"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "njwds-alert": NjwdsAlert;
        "njwds-banner": NjwdsBanner;
        "njwds-button": NjwdsButton;
        "njwds-radio": NjwdsRadio;
        "njwds-radio-group": NjwdsRadioGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "njwds-alert": LocalJSX.NjwdsAlert & JSXBase.HTMLAttributes<HTMLNjwdsAlertElement>;
            "njwds-banner": LocalJSX.NjwdsBanner & JSXBase.HTMLAttributes<HTMLNjwdsBannerElement>;
            "njwds-button": LocalJSX.NjwdsButton & JSXBase.HTMLAttributes<HTMLNjwdsButtonElement>;
            "njwds-radio": LocalJSX.NjwdsRadio & JSXBase.HTMLAttributes<HTMLNjwdsRadioElement>;
            "njwds-radio-group": LocalJSX.NjwdsRadioGroup & JSXBase.HTMLAttributes<HTMLNjwdsRadioGroupElement>;
        }
    }
}
