/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonVariant } from "./components/button/button";
import { Mode } from "./interface";
import { NjwdsChangeEventDetail, NjwdsInvalidEventDetail, RadioGroupValidityState } from "./components/radio-group/radio-group";
export { ButtonVariant } from "./components/button/button";
export { Mode } from "./interface";
export { NjwdsChangeEventDetail, NjwdsInvalidEventDetail, RadioGroupValidityState } from "./components/radio-group/radio-group";
export namespace Components {
    interface NjwdsAlert {
        "noIcon": boolean;
        "slim": boolean;
        "type": "default" | "info" | "warning" | "error" | "emergency";
    }
    interface NjwdsBanner {
    }
    interface NjwdsButton {
        "asChild": boolean;
        "mode": Mode;
        "variant": ButtonVariant;
    }
    interface NjwdsRadio {
        "error": boolean;
        "inputId": string;
        "tile": boolean;
        "value": string;
    }
    interface NjwdsRadioGroup {
        "getValidity": () => Promise<RadioGroupValidityState>;
        "name": string;
        "required": boolean;
        "showValidity": boolean;
        "tile": boolean;
        "validationMessage": string;
        "value": string;
    }
}
export interface NjwdsRadioGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNjwdsRadioGroupElement;
}
declare global {
    interface HTMLNjwdsAlertElement extends Components.NjwdsAlert, HTMLStencilElement {
    }
    var HTMLNjwdsAlertElement: {
        prototype: HTMLNjwdsAlertElement;
        new (): HTMLNjwdsAlertElement;
    };
    interface HTMLNjwdsBannerElement extends Components.NjwdsBanner, HTMLStencilElement {
    }
    var HTMLNjwdsBannerElement: {
        prototype: HTMLNjwdsBannerElement;
        new (): HTMLNjwdsBannerElement;
    };
    interface HTMLNjwdsButtonElement extends Components.NjwdsButton, HTMLStencilElement {
    }
    var HTMLNjwdsButtonElement: {
        prototype: HTMLNjwdsButtonElement;
        new (): HTMLNjwdsButtonElement;
    };
    interface HTMLNjwdsRadioElement extends Components.NjwdsRadio, HTMLStencilElement {
    }
    var HTMLNjwdsRadioElement: {
        prototype: HTMLNjwdsRadioElement;
        new (): HTMLNjwdsRadioElement;
    };
    interface HTMLNjwdsRadioGroupElementEventMap {
        "njwdsChange": NjwdsChangeEventDetail;
        "njwdsInvalid": NjwdsInvalidEventDetail;
    }
    interface HTMLNjwdsRadioGroupElement extends Components.NjwdsRadioGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNjwdsRadioGroupElementEventMap>(type: K, listener: (this: HTMLNjwdsRadioGroupElement, ev: NjwdsRadioGroupCustomEvent<HTMLNjwdsRadioGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNjwdsRadioGroupElementEventMap>(type: K, listener: (this: HTMLNjwdsRadioGroupElement, ev: NjwdsRadioGroupCustomEvent<HTMLNjwdsRadioGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNjwdsRadioGroupElement: {
        prototype: HTMLNjwdsRadioGroupElement;
        new (): HTMLNjwdsRadioGroupElement;
    };
    interface HTMLElementTagNameMap {
        "njwds-alert": HTMLNjwdsAlertElement;
        "njwds-banner": HTMLNjwdsBannerElement;
        "njwds-button": HTMLNjwdsButtonElement;
        "njwds-radio": HTMLNjwdsRadioElement;
        "njwds-radio-group": HTMLNjwdsRadioGroupElement;
    }
}
declare namespace LocalJSX {
    interface NjwdsAlert {
        "noIcon"?: boolean;
        "slim"?: boolean;
        "type"?: "default" | "info" | "warning" | "error" | "emergency";
    }
    interface NjwdsBanner {
    }
    interface NjwdsButton {
        "asChild"?: boolean;
        "mode"?: Mode;
        "variant"?: ButtonVariant;
    }
    interface NjwdsRadio {
        "error"?: boolean;
        "inputId": string;
        "tile"?: boolean;
        "value": string;
    }
    interface NjwdsRadioGroup {
        "name": string;
        "onNjwdsChange"?: (event: NjwdsRadioGroupCustomEvent<NjwdsChangeEventDetail>) => void;
        "onNjwdsInvalid"?: (event: NjwdsRadioGroupCustomEvent<NjwdsInvalidEventDetail>) => void;
        "required"?: boolean;
        "showValidity"?: boolean;
        "tile"?: boolean;
        "validationMessage"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "njwds-alert": NjwdsAlert;
        "njwds-banner": NjwdsBanner;
        "njwds-button": NjwdsButton;
        "njwds-radio": NjwdsRadio;
        "njwds-radio-group": NjwdsRadioGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "njwds-alert": LocalJSX.NjwdsAlert & JSXBase.HTMLAttributes<HTMLNjwdsAlertElement>;
            "njwds-banner": LocalJSX.NjwdsBanner & JSXBase.HTMLAttributes<HTMLNjwdsBannerElement>;
            "njwds-button": LocalJSX.NjwdsButton & JSXBase.HTMLAttributes<HTMLNjwdsButtonElement>;
            "njwds-radio": LocalJSX.NjwdsRadio & JSXBase.HTMLAttributes<HTMLNjwdsRadioElement>;
            "njwds-radio-group": LocalJSX.NjwdsRadioGroup & JSXBase.HTMLAttributes<HTMLNjwdsRadioGroupElement>;
        }
    }
}
